const GOLDEN_ANGLE=Math.PI*(3-Math.sqrt(5));
const TAU=Math.PI*2;
const COLORS=['#15c7ff','#ffd54f','#ff4fc3','#9cff57','#ff9d3d','#a88cff'];
const canvas=document.getElementById('spiral');
const ctx=canvas.getContext('2d');
let mode='field',peopleCount=2,primeCache={limit:0,list:[]};

const $=id=>document.getElementById(id);
const deg=r=>r*180/Math.PI;
const mod=(a,m)=>((a%m)+m)%m;

function parseDob(v){const[y,m,d]=v.split('-').map(Number);if(!y||!m||!d)throw new Error('Enter a valid date.');return{year:y,month:m,day:d}}
function profile(name,dob,colour){const{year,month,day}=parseDob(dob);const n=year*month;return{name:(name||'Unnamed').trim(),dob,year,month,day,n,dayMod:day,dayArm:n%day,monthMod:month,monthArm:n%month,colour}}
function radius(index,geometry,scale){return(geometry==='linear'?index:Math.sqrt(index))*scale}
function point(index,geometry,scale,c){const r=radius(index,geometry,scale),t=index*GOLDEN_ANGLE;return{x:c+r*Math.cos(t),y:c+r*Math.sin(t),r,t}}
function scaleFor(maxIndex,geometry){const basis=geometry==='linear'?Math.max(1,maxIndex):Math.sqrt(Math.max(1,maxIndex));return canvas.width*.455/basis}
function clear(){ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.shadowBlur=0;ctx.setLineDash([])}
function rgba(hex,a){const h=hex.replace('#',''),n=parseInt(h.length===3?h.split('').map(x=>x+x).join(''):h,16);return`rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}

function primes(limit){if(primeCache.limit>=limit)return primeCache.list.filter(x=>x<limit);const s=new Uint8Array(limit+1);s.fill(1,2);for(let p=2;p*p<=limit;p++)if(s[p])for(let k=p*p;k<=limit;k+=p)s[k]=0;const list=[];for(let i=2;i<=limit;i++)if(s[i])list.push(i);primeCache={limit,list};return list}
function baseField(maxIndex,limit,geometry,kind='full',alpha=.18){const c=canvas.width/2,count=Math.min(maxIndex,limit),scale=scaleFor(maxIndex,geometry);ctx.fillStyle=kind==='prime'?'rgba(21,199,255,.52)':`rgba(55,72,90,${alpha})`;const indices=kind==='prime'?primes(count):null;if(indices){for(const i of indices){const p=point(i,geometry,scale,c);ctx.fillRect(p.x,p.y,1.25,1.25)}}else{for(let i=0;i<count;i++){const p=point(i,geometry,scale,c);ctx.fillRect(p.x,p.y,1,1)}}return{c,scale,count}}
function recurrence(count,geometry,scale,c){[13,21,34,55,89,144].forEach((step,layer)=>{ctx.strokeStyle=`rgba(255,255,255,${.032+layer*.006})`;ctx.lineWidth=.38;for(let o=0;o<Math.min(step,12);o++){ctx.beginPath();let started=false;for(let i=o;i<count;i+=step*18){const p=point(i,geometry,scale,c);if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y)}ctx.stroke()}})}
function residue(modulus,arm,colour,maxIndex,geometry,scale,c,size=1.55,alpha=.72){ctx.fillStyle=rgba(colour,alpha);for(let i=arm;i<maxIndex;i+=modulus){const p=point(i,geometry,scale,c);ctx.fillRect(p.x-size/2,p.y-size/2,size,size)}}
function marker(p,geometry,scale,c){const q=point(p.n,geometry,scale,c);ctx.strokeStyle='rgba(255,255,255,.4)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(c,c);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.save();ctx.shadowBlur=18;ctx.shadowColor=p.colour;ctx.fillStyle=p.colour;ctx.beginPath();ctx.arc(q.x,q.y,7,0,TAU);ctx.fill();ctx.restore();ctx.fillStyle='#fff';ctx.font='13px Inter,system-ui,sans-serif';[p.name,`${String(p.day).padStart(2,'0')}/${String(p.month).padStart(2,'0')}/${p.year}`,`n = ${p.n.toLocaleString()}`].forEach((x,i)=>ctx.fillText(x,q.x+10,q.y-12+i*14));return q}

function big5(p){const clamp=x=>Math.max(0,Math.min(100,Math.round(x*100)/100));const n=p.n,m=p.dayMod,a=p.dayArm;return{Openness:clamp(70+(m%7)*4+(n%13)*.5),Conscientiousness:clamp(60+mod(m-a,m)*3-(n%10)),Extraversion:clamp(50-Math.abs(a-m/2)*5+(n%7)),Agreeableness:clamp(40+(a%5)*6-(n%9)),Neuroticism:clamp(30+((a*3)%17)+10000/Math.max(1,n))}}
function legacyIndex(p){return p.n*p.dayArm/Math.max(1,p.dayMod)}
function octaveFamily(p,lo=40,hi=4000){const b=Math.abs(legacyIndex(p));if(!Number.isFinite(b)||b<=0)return[];const out=[];for(let k=-14;k<=14;k++){const v=b*Math.pow(2,k);if(v>=lo&&v<=hi)out.push(v)}return[...new Set(out.map(v=>Math.round(v*1000)/1000))].sort((a,b)=>a-b)}
function harmonic(p){const dayDelta=mod(p.dayMod*GOLDEN_ANGLE,TAU),monthDelta=mod(p.monthMod*GOLDEN_ANGLE,TAU);const returns=[];for(let k=1;k<=12;k++){const a=mod(k*p.dayMod*GOLDEN_ANGLE,TAU),cycles=a/TAU;returns.push({k,angle:a,cycles,returnDistance:Math.min(cycles,1-cycles)})}returns.sort((a,b)=>a.returnDistance-b.returnDistance);return{dayDelta,monthDelta,dayCycles:dayDelta/TAU,monthCycles:monthDelta/TAU,returns}}
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)}
function lcm(a,b){return Math.abs(a*b)/gcd(a,b)}
function smallestAngle(a){const n=mod(a,TAU);return Math.min(n,TAU-n)}
function firstShared(a1,m1,a2,m2){const period=lcm(m1,m2);for(let x=0;x<period;x++)if(x%m1===mod(a1,m1)&&x%m2===mod(a2,m2))return x;return null}

function renderLegend(items){$('legend').innerHTML=items.map(x=>`<span><i class="swatch" style="background:${x.colour}"></i>${esc(x.label)}</span>`).join('')}
function metrics(items){$('summary').innerHTML=items.map(x=>`<div class="metric"><span>${esc(x.label)}</span><strong>${esc(x.value)}</strong></div>`).join('')}
function hideTables(){['harmonicsSection','big5Section','relationshipSection'].forEach(id=>$(id).classList.add('hidden'))}
function renderHarmonics(ps){let h='<tr><th>Person</th><th>Day fundamental</th><th>Month fundamental</th><th>Day cycles</th><th>Legacy index</th><th>Octave family</th><th>Closest returns</th></tr>';for(const p of ps){const x=harmonic(p),oct=octaveFamily(p),returns=x.returns.slice(0,4).map(r=>`${r.k}×: ${r.returnDistance.toFixed(6)}`).join('<br>');h+=`<tr><td>${esc(p.name)}</td><td>${deg(x.dayDelta).toFixed(3)}°</td><td>${deg(x.monthDelta).toFixed(3)}°</td><td>${x.dayCycles.toFixed(6)}</td><td>${legacyIndex(p).toFixed(3)}</td><td>${oct.length?oct.map(v=>v.toFixed(3)).join('<br>'):'—'}</td><td>${returns}</td></tr>`}$('harmonicsTable').innerHTML=h;$('harmonicsSection').classList.remove('hidden')}
function renderBig5(ps){let h='<tr><th>Person</th><th>Openness</th><th>Conscientiousness</th><th>Extraversion</th><th>Agreeableness</th><th>Neuroticism</th></tr>';for(const p of ps){const b=big5(p);h+=`<tr><td>${esc(p.name)}</td><td>${b.Openness}</td><td>${b.Conscientiousness}</td><td>${b.Extraversion}</td><td>${b.Agreeableness}</td><td>${b.Neuroticism}</td></tr>`}$('big5Table').innerHTML=h;$('big5Section').classList.remove('hidden')}
function renderRelationship(rows){let h='<tr><th>Pair</th><th>Angular sep.</th><th>Δr</th><th>Distance</th><th>gcd</th><th>lcm</th><th>Shared nodes</th><th>First shared</th><th>Beat angle</th></tr>';for(const r of rows)h+=`<tr><td>${esc(r.pair)}</td><td>${r.angular}</td><td>${r.radial}</td><td>${r.distance}</td><td>${r.g}</td><td>${r.l}</td><td>${r.shared}</td><td>${r.first}</td><td>${r.beat}</td></tr>`;$('relationshipTable').innerHTML=h;$('relationshipSection').classList.remove('hidden')}

function fieldMode(){mode='field';clear();hideTables();const count=+$('fieldPoints').value,overlay=$('fieldOverlay').value,geometry=$('fieldGeometry').value,c=canvas.width/2,scale=scaleFor(count,geometry);if(overlay==='primes'){ctx.fillStyle='rgba(21,199,255,.85)';for(const i of primes(count)){const p=point(i,geometry,scale,c);ctx.fillRect(p.x,p.y,1.45,1.45)}renderLegend([{label:'Prime field',colour:'#15c7ff'}])}else{ctx.fillStyle='rgba(21,199,255,.50)';for(let i=0;i<count;i++){const p=point(i,geometry,scale,c);ctx.fillRect(p.x,p.y,1,1)}if(overlay==='recurrence')recurrence(count,geometry,scale,c);renderLegend([{label:'Signal field',colour:'#15c7ff'},...(overlay==='recurrence'?[{label:'Recursive resonance',colour:'#ffffff'}]:[])])}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(c,c,3,0,TAU);ctx.fill();metrics([{label:'Field points',value:count.toLocaleString()},{label:'Golden angle',value:'137.507764°'},{label:'Radius',value:geometry==='sqrt'?'√n — equal-area':'n — linear traversal'}])}

function individualMode(){mode='individual';clear();hideTables();try{const p=profile($('individualName').value,$('individualDob').value,COLORS[0]),view=$('individualView').value,background=$('individualBackground').value,geometry=$('individualGeometry').value,fieldPoints=+$('individualPoints').value,maxIndex=Math.max(fieldPoints,p.n+500),c=canvas.width/2,scale=scaleFor(maxIndex,geometry);if(view==='field'||view==='overlay')baseField(maxIndex,fieldPoints,geometry,background,.16);if(view==='arc'||view==='overlay'){residue(p.monthMod,p.monthArm,COLORS[1],maxIndex,geometry,scale,c,1.15,.38);residue(p.dayMod,p.dayArm,p.colour,maxIndex,geometry,scale,c,1.7,.8);marker(p,geometry,scale,c)}const leg=[];if(view!=='field'){leg.push({label:`${p.dayMod}-field day arc`,colour:p.colour},{label:`${p.monthMod}-field month anchor`,colour:COLORS[1]})}if(view!=='arc')leg.push({label:`${background==='prime'?'Prime':'Full'} consciousness field`,colour:'#4a5c70'});renderLegend(leg);const h=harmonic(p),oct=octaveFamily(p);metrics([{label:'Traversal index',value:p.n.toLocaleString()},{label:'Day residue',value:`${p.dayArm} mod ${p.dayMod}`},{label:'Month residue',value:`${p.monthArm} mod ${p.monthMod}`},{label:'Day fundamental',value:`${deg(h.dayDelta).toFixed(3)}°`},{label:'Legacy harmonic index',value:legacyIndex(p).toFixed(3)},{label:'Octave family',value:oct.length?oct.map(v=>v.toFixed(3)).join(' · '):'—'}]);renderHarmonics([p]);renderBig5([p])}catch(e){metrics([{label:'Error',value:e.message}])}}

function relationshipMode(){mode='relationship';clear();hideTables();try{const ps=collectPeople(),view=$('relationshipView').value,geometry=$('relationshipGeometry').value,fieldPoints=+$('relationshipPoints').value,maxIndex=Math.max(fieldPoints,...ps.map(p=>p.n+800)),c=canvas.width/2,scale=scaleFor(maxIndex,geometry),pts=[];if(view==='field'||view==='overlay')baseField(maxIndex,fieldPoints,geometry,'full',.12);for(const p of ps){if(view==='arcs'||view==='overlay'){residue(p.dayMod,p.dayArm,p.colour,maxIndex,geometry,scale,c,1.5,.72);pts.push(marker(p,geometry,scale,c))}else pts.push(point(p.n,geometry,scale,c))}if(view!=='field')connections(pts,$('relationshipConnections').value);renderLegend(view==='field'?[{label:'Shared consciousness field',colour:'#4a5c70'}]:ps.map(p=>({label:`${p.name}: ${p.dayArm} mod ${p.dayMod}`,colour:p.colour})));const rows=[],cards=[];for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j],angular=smallestAngle(a.n*GOLDEN_ANGLE-b.n*GOLDEN_ANGLE),radial=Math.abs(Math.sqrt(a.n)-Math.sqrt(b.n)),dx=(pts[i].x-pts[j].x)/scale,dy=(pts[i].y-pts[j].y)/scale,distance=Math.hypot(dx,dy),g=gcd(a.dayMod,b.dayMod),l=lcm(a.dayMod,b.dayMod),shared=mod(a.dayArm-b.dayArm,g)===0,first=shared?firstShared(a.dayArm,a.dayMod,b.dayArm,b.dayMod):null,beat=smallestAngle(harmonic(a).dayDelta-harmonic(b).dayDelta);rows.push({pair:`${a.name} ↔ ${b.name}`,angular:`${deg(angular).toFixed(2)}°`,radial:radial.toFixed(3),distance:distance.toFixed(3),g,l,shared:shared?'Yes':'No',first:shared?`${first} (every ${l})`:'—',beat:`${deg(beat).toFixed(2)}°`});cards.push({label:`${a.name} ↔ ${b.name}`,value:`${deg(angular).toFixed(1)}° · Δr ${radial.toFixed(1)} · d ${distance.toFixed(1)}`})}metrics([{label:'People',value:String(ps.length)},{label:'Max traversal',value:Math.max(...ps.map(p=>p.n)).toLocaleString()},{label:'Geometry',value:geometry==='sqrt'?'√n — equal-area':'n — linear'},...cards]);renderHarmonics(ps);renderBig5(ps);renderRelationship(rows)}catch(e){metrics([{label:'Error',value:e.message}])}}

function connections(pts,type){if(type==='none')return;ctx.strokeStyle='rgba(255,255,255,.52)';ctx.lineWidth=1.15;ctx.setLineDash([6,7]);if(type==='polygon'){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke()}else for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){ctx.beginPath();ctx.moveTo(pts[i].x,pts[i].y);ctx.lineTo(pts[j].x,pts[j].y);ctx.stroke()}ctx.setLineDash([])}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function peopleDefaults(){return[{name:'Nathan',dob:'1977-12-29'},{name:'Bec',dob:'1984-11-13'},{name:'Izzy',dob:'2019-07-07'},{name:'Tay',dob:'2018-05-04'}]}
function renderPeople(){const grid=$('peopleGrid'),existing=[...grid.querySelectorAll('.person')].map(x=>({name:x.querySelector('.name')?.value,dob:x.querySelector('.dob')?.value})),defs=peopleDefaults();grid.innerHTML='';for(let i=0;i<peopleCount;i++){const v=existing[i]||defs[i]||{name:`Person ${i+1}`,dob:'2000-01-01'};grid.insertAdjacentHTML('beforeend',`<div class="card person"><h3><i class="swatch" style="background:${COLORS[i]}"></i>Person ${i+1}</h3><label>Name<input class="name" value="${esc(v.name)}"></label><label>Date of birth<input class="dob" type="date" value="${v.dob}"></label></div>`)}}
function collectPeople(){return[...document.querySelectorAll('.person')].map((x,i)=>profile(x.querySelector('.name').value,x.querySelector('.dob').value,COLORS[i]))}
function activate(next){mode=next;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.id===next));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===next));({field:fieldMode,individual:individualMode,relationship:relationshipMode})[next]()}
function share(){const q=new URLSearchParams({mode});if(mode==='individual'){q.set('name',$('individualName').value);q.set('dob',$('individualDob').value)}if(mode==='relationship')q.set('people',JSON.stringify(collectPeople().map(({name,dob})=>({name,dob}))));const url=`${location.origin}${location.pathname}?${q}`;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(url).then(()=>alert('Share link copied.')).catch(()=>prompt('Copy this link:',url));else prompt('Copy this link:',url)}
function download(){const a=document.createElement('a');a.download=`signal-spiral-${mode}.png`;a.href=canvas.toDataURL('image/png');a.click()}

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.mode)));
$('renderField').addEventListener('click',fieldMode);$('renderIndividual').addEventListener('click',individualMode);$('renderRelationship').addEventListener('click',relationshipMode);$('addPerson').addEventListener('click',()=>{if(peopleCount<6){peopleCount++;renderPeople()}});$('removePerson').addEventListener('click',()=>{if(peopleCount>2){peopleCount--;renderPeople()}});$('downloadPng').addEventListener('click',download);$('copyLink').addEventListener('click',share);
renderPeople();
const qs=new URLSearchParams(location.search);if(qs.get('name'))$('individualName').value=qs.get('name');if(qs.get('dob'))$('individualDob').value=qs.get('dob');if(qs.get('people')){try{const list=JSON.parse(qs.get('people'));peopleCount=Math.max(2,Math.min(6,list.length));renderPeople();[...document.querySelectorAll('.person')].forEach((x,i)=>{x.querySelector('.name').value=list[i]?.name||`Person ${i+1}`;x.querySelector('.dob').value=list[i]?.dob||'2000-01-01'})}catch{}}
activate(['field','individual','relationship'].includes(qs.get('mode'))?qs.get('mode'):'field');
